Unofficial release of LibVLCSharp.Avalonia to solve some issues
videolan/libvlcsharp pull request #294
Opened 2022-04-05 17:06 UTC by radiolondra

### Description of Change ###

Created new VideoView.cs

### Issues Resolved ### 

- Embed LibVLCSharp Avalonia VLC VideoView in Avalonia UserControl

- Put and use an Avalonia UserControl on top of VideoView (VLC MediaPlayer), for example, a set of buttons/controls to control the VLC MediaPlayer.

- fixes #525

### API Changes ###

 None

### Platforms Affected ### 
- Avalonia

### Behavioral/Visual Changes ###
Users can embed VideoView in Avalonia UserControl (not only in a window)
Users can put a UserControl on top of MediaPlayer

### Before/After Screenshots ### 
See (after)screenshots in LibVLCSharp.Avalonia.Unofficial.Samples README.md

### Testing Procedure ###
See the LibVLCSharp.Avalonia.Unofficial.Samples added to the repo.

### PR Checklist ###

- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

2022-04-06 05:48 UTC, mfkl requested changes
Hi there,

Thanks for your PR!

I have a few notes though, see my comments in the thread.

For the samples, I think we should do the same as for the WPF samples. No need to add new projects or SLN files, we can just have 2 buttons on the main window of the app, and the user can select either scenarios to test!

Let us know if you have any questions regarding the comments :)

2022-04-06 05:48 UTC, mfkl commented on src/LibVLCSharp.Avalonia.Unofficial/LibVLCSharp.Avalonia.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Why create a new Unofficial package? IMO this csproj is not needed, we can use the current one https://github.com/videolan/libvlcsharp/blob/3.x/src/LibVLCSharp.Avalonia/LibVLCSharp.Avalonia.csproj

2022-04-06 05:48 UTC, mfkl commented on src/LibVLCSharp.Avalonia.Unofficial/LibVLCSharp.Avalonia.sln
> +﻿
This sln is not needed as well, since we will re-use the current avalonia project.

2022-04-06 05:48 UTC, mfkl commented on src/LibVLCSharp.Avalonia.Unofficial/README.md
> +# LibVLCSharp.Avalonia.Unofficial
Thanks for these notes. They could likely be added to https://github.com/videolan/libvlcsharp/blob/3.x/src/LibVLCSharp.Avalonia/README.md

2022-04-06 05:48 UTC, mfkl commented on src/LibVLCSharp.Avalonia.Unofficial/VideoView.cs
> +using System.Reactive.Disposables;
We don't want to use System.Reactive for now, if we can do without.

2022-04-06 05:48 UTC, mfkl commented on src/LibVLCSharp.Avalonia.Unofficial/VideoView.cs
> +using CSharpFunctionalExtensions;
This is also a dependency that should be removed.

2022-04-06 05:48 UTC, mfkl commented on src/LibVLCSharp.Avalonia.Unofficial/VideoView.cs
> +using System;
So the existing videoview should be modified, to support these scenarios. Much like the WPF videoview.

2022-04-07 11:40 UTC, radiolondra commented
Martin,

thank you for the time you spent to review my PR.

I created a new Unofficial project for LibVLCSharp.Avalonia to give people the ability to choose between a partially working solution (Original project) and this Unofficial solution which, in a way or another, covers all the Avalonia's users requests (VideoView inside an Avalonia UserControl and a dynamic layer on top of the MediaPlayer).

I perfecty understand your requests to change VideoView code, to satisfy the rules Videolan in some way imposes, so that this Unofficial solution can became the ONLY solution for Avalonia users. In this regard I would like to mention that ReactiveUI is now widely used, at least in .NET 5/6 with Avalonia.

However, the required changes need several time, both in coding and, especially, in testing. And, at this moment, I don't have this time available.

Therefore, feel free to reject my PR. Interested users will still be able to find the solution to their requests and questions using other ways.

I thank you anyway for your attention to the project.

Have a serene day.
Roberto

2022-04-19 09:41 UTC, mfkl commented
> However, the required changes need several time, both in coding and, especially, in testing. And, at this moment, I don't have this time available.

Well, that's too bad. If you can, keep your code available so that community members may be able to work on getting it merged to libvlcsharp.avalonia proper.

Cheers!

2022-04-19 09:41 UTC, closed without merging

2024-08-15 08:48 UTC, JMND3v commented
> Martin,
> 
> thank you for the time you spent to review my PR.
> 
> I created a new Unofficial project for LibVLCSharp.Avalonia to give people the ability to choose between a partially working solution (Original project) and this Unofficial solution which, in a way or another, covers all the Avalonia's users requests (VideoView inside an Avalonia UserControl and a dynamic layer on top of the MediaPlayer).
> 
> I perfecty understand your requests to change VideoView code, to satisfy the rules Videolan in some way imposes, so that this Unofficial solution can became the ONLY solution for Avalonia users. In this regard I would like to mention that ReactiveUI is now widely used, at least in .NET 5/6 with Avalonia.
> 
> However, the required changes need several time, both in coding and, especially, in testing. And, at this moment, I don't have this time available.
> 
> Therefore, feel free to reject my PR. Interested users will still be able to find the solution to their requests and questions using the links at the bottom of this post.
> 
> I thank you anyway for your attention to the project.
> 
> Have a serene day.
> Roberto
> 
> ### Avalonia Unofficial LibVLCSharp External Links
> **VLC video player inside an Avalonia Window/UserControl embedding single static customizable control (e.g.player buttons)**
> [LibVLCSharp.Avalonia.Unofficial](https://github.com/radiolondra/libvlcsharp/tree/3.x/src/LibVLCSharp.Avalonia.Unofficial)
> 
> **VLC video player inside an Avalonia Window/UserControl embedding multiple draggable customizable controls (e.g.player buttons, images,...)**
> [LibVLCSharp.Avalonia.Unofficial.UCanvas](https://github.com/radiolondra/libvlcsharp/tree/3.x/src/LibVLCSharp.Avalonia.Unofficial.UCanvas)
> 
> **LibVLCSharp.Avalonia.Unofficial Samples**
> [LibVLCSharp.Avalonia.Unofficial.Samples](https://github.com/radiolondra/libvlcsharp/tree/3.x/samples/LibVLCSharp.Avalonia.Unofficial.Samples)
> 
> **LibVLCSharp.Avalonia.Unofficial.UCanvas sample**
> [LibVLCSharp.Avalonia.Unofficial.UCanvas.Samples](https://github.com/radiolondra/libvlcsharp/tree/3.x/samples/LibVLCSharp.Avalonia.Unofficial.UCanvas.Samples)
> 
> **YAMP 2 - Open source video player sample using LibVLCSharp.Avalonia.Unofficial library**
> [Github sources](https://github.com/radiolondra/YAMP2)
> [**Watch YAMP2 in action**](https://www.screencast.com/t/uTGBnpE6v)
> 
> 

Has this been showcased already? The Avalonia community needs to know this wonderful contribution!